export interface Country {
  code: string;
  name: string;
  currency: string;
  flag: string;
}

export const countries: Country[] = [
  { code: 'AD', name: 'Andorra', currency: 'EUR', flag: '🇦🇩' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', flag: '🇦🇪' },
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', flag: '🇦🇫' },
  { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD', flag: '🇦🇬' },
  { code: 'AI', name: 'Anguilla', currency: 'XCD', flag: '🇦🇮' },
  { code: 'AL', name: 'Albania', currency: 'ALL', flag: '🇦🇱' },
  { code: 'AM', name: 'Armenia', currency: 'AMD', flag: '🇦🇲' },
  { code: 'AO', name: 'Angola', currency: 'AOA', flag: '🇦🇴' },
  { code: 'AQ', name: 'Antarctica', currency: 'USD', flag: '🇦🇶' },
  { code: 'AR', name: 'Argentina', currency: 'ARS', flag: '🇦🇷' },
  { code: 'AS', name: 'American Samoa', currency: 'USD', flag: '🇦🇸' },
  { code: 'AT', name: 'Austria', currency: 'EUR', flag: '🇦🇹' },
  { code: 'AU', name: 'Australia', currency: 'AUD', flag: '🇦🇺' },
  { code: 'AW', name: 'Aruba', currency: 'AWG', flag: '🇦🇼' },
  { code: 'AX', name: 'Åland Islands', currency: 'EUR', flag: '🇦🇽' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', flag: '🇦🇿' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM', flag: '🇧🇦' },
  { code: 'BB', name: 'Barbados', currency: 'BBD', flag: '🇧🇧' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', flag: '🇧🇩' },
  { code: 'BE', name: 'Belgium', currency: 'EUR', flag: '🇧🇪' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', flag: '🇧🇫' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN', flag: '🇧🇬' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD', flag: '🇧🇭' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', flag: '🇧🇮' },
  { code: 'BJ', name: 'Benin', currency: 'XOF', flag: '🇧🇯' },
  { code: 'BL', name: 'Saint Barthélemy', currency: 'EUR', flag: '🇧🇱' },
  { code: 'BM', name: 'Bermuda', currency: 'BMD', flag: '🇧🇲' },
  { code: 'BN', name: 'Brunei', currency: 'BND', flag: '🇧🇳' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', flag: '🇧🇴' },
  { code: 'BQ', name: 'Caribbean Netherlands', currency: 'USD', flag: '🇧🇶' },
  { code: 'BR', name: 'Brazil', currency: 'BRL', flag: '🇧🇷' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', flag: '🇧🇸' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN', flag: '🇧🇹' },
  { code: 'BV', name: 'Bouvet Island', currency: 'NOK', flag: '🇧🇻' },
  { code: 'BW', name: 'Botswana', currency: 'BWP', flag: '🇧🇼' },
  { code: 'BY', name: 'Belarus', currency: 'BYN', flag: '🇧🇾' },
  { code: 'BZ', name: 'Belize', currency: 'BZD', flag: '🇧🇿' },
  { code: 'CA', name: 'Canada', currency: 'CAD', flag: '🇨🇦' },
  { code: 'CC', name: 'Cocos Islands', currency: 'AUD', flag: '🇨🇨' },
  { code: 'CD', name: 'Democratic Republic of the Congo', currency: 'CDF', flag: '🇨🇩' },
  { code: 'CF', name: 'Central African Republic', currency: 'XAF', flag: '🇨🇫' },
  { code: 'CG', name: 'Republic of the Congo', currency: 'XAF', flag: '🇨🇬' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', flag: '🇨🇭' },
  { code: 'CI', name: 'Côte d\'Ivoire', currency: 'XOF', flag: '🇨🇮' },
  { code: 'CK', name: 'Cook Islands', currency: 'NZD', flag: '🇨🇰' },
  { code: 'CL', name: 'Chile', currency: 'CLP', flag: '🇨🇱' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', flag: '🇨🇲' },
  { code: 'CN', name: 'China', currency: 'CNY', flag: '🇨🇳' },
  { code: 'CO', name: 'Colombia', currency: 'COP', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', flag: '🇨🇷' },
  { code: 'CU', name: 'Cuba', currency: 'CUP', flag: '🇨🇺' },
  { code: 'CV', name: 'Cape Verde', currency: 'CVE', flag: '🇨🇻' },
  { code: 'CW', name: 'Curaçao', currency: 'ANG', flag: '🇨🇼' },
  { code: 'CX', name: 'Christmas Island', currency: 'AUD', flag: '🇨🇽' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR', flag: '🇨🇾' },
  { code: 'CZ', name: 'Czech Republic', currency: 'CZK', flag: '🇨🇿' },
  { code: 'DE', name: 'Germany', currency: 'EUR', flag: '🇩🇪' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', flag: '🇩🇯' },
  { code: 'DK', name: 'Denmark', currency: 'DKK', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', currency: 'XCD', flag: '🇩🇲' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP', flag: '🇩🇴' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', flag: '🇩🇿' },
  { code: 'EC', name: 'Ecuador', currency: 'USD', flag: '🇪🇨' },
  { code: 'EE', name: 'Estonia', currency: 'EUR', flag: '🇪🇪' },
  { code: 'EG', name: 'Egypt', currency: 'EGP', flag: '🇪🇬' },
  { code: 'EH', name: 'Western Sahara', currency: 'MAD', flag: '🇪🇭' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', flag: '🇪🇷' },
  { code: 'ES', name: 'Spain', currency: 'EUR', flag: '🇪🇸' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', flag: '🇪🇹' },
  { code: 'FI', name: 'Finland', currency: 'EUR', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD', flag: '🇫🇯' },
  { code: 'FK', name: 'Falkland Islands', currency: 'FKP', flag: '🇫🇰' },
  { code: 'FM', name: 'Micronesia', currency: 'USD', flag: '🇫🇲' },
  { code: 'FO', name: 'Faroe Islands', currency: 'DKK', flag: '🇫🇴' },
  { code: 'FR', name: 'France', currency: 'EUR', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabon', currency: 'XAF', flag: '🇬🇦' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', flag: '🇬🇧' },
  { code: 'GD', name: 'Grenada', currency: 'XCD', flag: '🇬🇩' },
  { code: 'GE', name: 'Georgia', currency: 'GEL', flag: '🇬🇪' },
  { code: 'GF', name: 'French Guiana', currency: 'EUR', flag: '🇬🇫' },
  { code: 'GG', name: 'Guernsey', currency: 'GBP', flag: '🇬🇬' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', currency: 'GIP', flag: '🇬🇮' },
  { code: 'GL', name: 'Greenland', currency: 'DKK', flag: '🇬🇱' },
  { code: 'GM', name: 'Gambia', currency: 'GMD', flag: '🇬🇲' },
  { code: 'GN', name: 'Guinea', currency: 'GNF', flag: '🇬🇳' },
  { code: 'GP', name: 'Guadeloupe', currency: 'EUR', flag: '🇬🇵' },
  { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', flag: '🇬🇶' },
  { code: 'GR', name: 'Greece', currency: 'EUR', flag: '🇬🇷' },
  { code: 'GS', name: 'South Georgia', currency: 'GBP', flag: '🇬🇸' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', flag: '🇬🇹' },
  { code: 'GU', name: 'Guam', currency: 'USD', flag: '🇬🇺' },
  { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF', flag: '🇬🇼' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', flag: '🇬🇾' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', flag: '🇭🇰' },
  { code: 'HM', name: 'Heard Island', currency: 'AUD', flag: '🇭🇲' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', flag: '🇭🇳' },
  { code: 'HR', name: 'Croatia', currency: 'EUR', flag: '🇭🇷' },
  { code: 'HT', name: 'Haiti', currency: 'HTG', flag: '🇭🇹' },
  { code: 'HU', name: 'Hungary', currency: 'HUF', flag: '🇭🇺' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', flag: '🇮🇩' },
  { code: 'IE', name: 'Ireland', currency: 'EUR', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', currency: 'ILS', flag: '🇮🇱' },
  { code: 'IM', name: 'Isle of Man', currency: 'GBP', flag: '🇮🇲' },
  { code: 'IN', name: 'India', currency: 'INR', flag: '🇮🇳' },
  { code: 'IO', name: 'British Indian Ocean Territory', currency: 'USD', flag: '🇮🇴' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD', flag: '🇮🇶' },
  { code: 'IR', name: 'Iran', currency: 'IRR', flag: '🇮🇷' },
  { code: 'IS', name: 'Iceland', currency: 'ISK', flag: '🇮🇸' },
  { code: 'IT', name: 'Italy', currency: 'EUR', flag: '🇮🇹' },
  { code: 'JE', name: 'Jersey', currency: 'GBP', flag: '🇯🇪' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', flag: '🇯🇲' },
  { code: 'JO', name: 'Jordan', currency: 'JOD', flag: '🇯🇴' },
  { code: 'JP', name: 'Japan', currency: 'JPY', flag: '🇯🇵' },
  { code: 'KE', name: 'Kenya', currency: 'KES', flag: '🇰🇪' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS', flag: '🇰🇬' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR', flag: '🇰🇭' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', flag: '🇰🇮' },
  { code: 'KM', name: 'Comoros', currency: 'KMF', flag: '🇰🇲' },
  { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD', flag: '🇰🇳' },
  { code: 'KP', name: 'North Korea', currency: 'KPW', flag: '🇰🇵' },
  { code: 'KR', name: 'South Korea', currency: 'KRW', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', flag: '🇰🇼' },
  { code: 'KY', name: 'Cayman Islands', currency: 'KYD', flag: '🇰🇾' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', flag: '🇰🇿' },
  { code: 'LA', name: 'Laos', currency: 'LAK', flag: '🇱🇦' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP', flag: '🇱🇧' },
  { code: 'LC', name: 'Saint Lucia', currency: 'XCD', flag: '🇱🇨' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', flag: '🇱🇮' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', flag: '🇱🇰' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', flag: '🇱🇷' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', flag: '🇱🇸' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', flag: '🇱🇺' },
  { code: 'LV', name: 'Latvia', currency: 'EUR', flag: '🇱🇻' },
  { code: 'LY', name: 'Libya', currency: 'LYD', flag: '🇱🇾' },
  { code: 'MA', name: 'Morocco', currency: 'MAD', flag: '🇲🇦' },
  { code: 'MC', name: 'Monaco', currency: 'EUR', flag: '🇲🇨' },
  { code: 'MD', name: 'Moldova', currency: 'MDL', flag: '🇲🇩' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', flag: '🇲🇪' },
  { code: 'MF', name: 'Saint Martin', currency: 'EUR', flag: '🇲🇫' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', flag: '🇲🇬' },
  { code: 'MH', name: 'Marshall Islands', currency: 'USD', flag: '🇲🇭' },
  { code: 'MK', name: 'North Macedonia', currency: 'MKD', flag: '🇲🇰' },
  { code: 'ML', name: 'Mali', currency: 'XOF', flag: '🇲🇱' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK', flag: '🇲🇲' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', flag: '🇲🇳' },
  { code: 'MO', name: 'Macao', currency: 'MOP', flag: '🇲🇴' },
  { code: 'MP', name: 'Northern Mariana Islands', currency: 'USD', flag: '🇲🇵' },
  { code: 'MQ', name: 'Martinique', currency: 'EUR', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', flag: '🇲🇷' },
  { code: 'MS', name: 'Montserrat', currency: 'XCD', flag: '🇲🇸' },
  { code: 'MT', name: 'Malta', currency: 'EUR', flag: '🇲🇹' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', flag: '🇲🇺' },
  { code: 'MV', name: 'Maldives', currency: 'MVR', flag: '🇲🇻' },
  { code: 'MW', name: 'Malawi', currency: 'MWK', flag: '🇲🇼' },
  { code: 'MX', name: 'Mexico', currency: 'MXN', flag: '🇲🇽' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', flag: '🇲🇾' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', flag: '🇲🇿' },
  { code: 'NA', name: 'Namibia', currency: 'NAD', flag: '🇳🇦' },
  { code: 'NC', name: 'New Caledonia', currency: 'XPF', flag: '🇳🇨' },
  { code: 'NE', name: 'Niger', currency: 'XOF', flag: '🇳🇪' },
  { code: 'NF', name: 'Norfolk Island', currency: 'AUD', flag: '🇳🇫' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', flag: '🇳🇬' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', flag: '🇳🇮' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', flag: '🇳🇱' },
  { code: 'NO', name: 'Norway', currency: 'NOK', flag: '🇳🇴' },
  { code: 'NP', name: 'Nepal', currency: 'NPR', flag: '🇳🇵' },
  { code: 'NR', name: 'Nauru', currency: 'AUD', flag: '🇳🇷' },
  { code: 'NU', name: 'Niue', currency: 'NZD', flag: '🇳🇺' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', flag: '🇳🇿' },
  { code: 'OM', name: 'Oman', currency: 'OMR', flag: '🇴🇲' },
  { code: 'PA', name: 'Panama', currency: 'PAB', flag: '🇵🇦' },
  { code: 'PE', name: 'Peru', currency: 'PEN', flag: '🇵🇪' },
  { code: 'PF', name: 'French Polynesia', currency: 'XPF', flag: '🇵🇫' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK', flag: '🇵🇬' },
  { code: 'PH', name: 'Philippines', currency: 'PHP', flag: '🇵🇭' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', flag: '🇵🇰' },
  { code: 'PL', name: 'Poland', currency: 'PLN', flag: '🇵🇱' },
  { code: 'PM', name: 'Saint Pierre and Miquelon', currency: 'EUR', flag: '🇵🇲' },
  { code: 'PN', name: 'Pitcairn', currency: 'NZD', flag: '🇵🇳' },
  { code: 'PR', name: 'Puerto Rico', currency: 'USD', flag: '🇵🇷' },
  { code: 'PS', name: 'Palestine', currency: 'ILS', flag: '🇵🇸' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', flag: '🇵🇹' },
  { code: 'PW', name: 'Palau', currency: 'USD', flag: '🇵🇼' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', flag: '🇵🇾' },
  { code: 'QA', name: 'Qatar', currency: 'QAR', flag: '🇶🇦' },
  { code: 'RE', name: 'Réunion', currency: 'EUR', flag: '🇷🇪' },
  { code: 'RO', name: 'Romania', currency: 'RON', flag: '🇷🇴' },
  { code: 'RS', name: 'Serbia', currency: 'RSD', flag: '🇷🇸' },
  { code: 'RU', name: 'Russia', currency: 'RUB', flag: '🇷🇺' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', flag: '🇷🇼' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', flag: '🇸🇦' },
  { code: 'SB', name: 'Solomon Islands', currency: 'SBD', flag: '🇸🇧' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', flag: '🇸🇨' },
  { code: 'SD', name: 'Sudan', currency: 'SDG', flag: '🇸🇩' },
  { code: 'SE', name: 'Sweden', currency: 'SEK', flag: '🇸🇪' },
  { code: 'SG', name: 'Singapore', currency: 'SGD', flag: '🇸🇬' },
  { code: 'SH', name: 'Saint Helena', currency: 'SHP', flag: '🇸🇭' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR', flag: '🇸🇮' },
  { code: 'SJ', name: 'Svalbard and Jan Mayen', currency: 'NOK', flag: '🇸🇯' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR', flag: '🇸🇰' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLE', flag: '🇸🇱' },
  { code: 'SM', name: 'San Marino', currency: 'EUR', flag: '🇸🇲' },
  { code: 'SN', name: 'Senegal', currency: 'XOF', flag: '🇸🇳' },
  { code: 'SO', name: 'Somalia', currency: 'SOS', flag: '🇸🇴' },
  { code: 'SR', name: 'Suriname', currency: 'SRD', flag: '🇸🇷' },
  { code: 'SS', name: 'South Sudan', currency: 'SSP', flag: '🇸🇸' },
  { code: 'ST', name: 'São Tomé and Príncipe', currency: 'STN', flag: '🇸🇹' },
  { code: 'SV', name: 'El Salvador', currency: 'USD', flag: '🇸🇻' },
  { code: 'SX', name: 'Sint Maarten', currency: 'ANG', flag: '🇸🇽' },
  { code: 'SY', name: 'Syria', currency: 'SYP', flag: '🇸🇾' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', flag: '🇸🇿' },
  { code: 'TC', name: 'Turks and Caicos Islands', currency: 'USD', flag: '🇹🇨' },
  { code: 'TD', name: 'Chad', currency: 'XAF', flag: '🇹🇩' },
  { code: 'TF', name: 'French Southern Territories', currency: 'EUR', flag: '🇹🇫' },
  { code: 'TG', name: 'Togo', currency: 'XOF', flag: '🇹🇬' },
  { code: 'TH', name: 'Thailand', currency: 'THB', flag: '🇹🇭' },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS', flag: '🇹🇯' },
  { code: 'TK', name: 'Tokelau', currency: 'NZD', flag: '🇹🇰' },
  { code: 'TL', name: 'Timor-Leste', currency: 'USD', flag: '🇹🇱' },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT', flag: '🇹🇲' },
  { code: 'TN', name: 'Tunisia', currency: 'TND', flag: '🇹🇳' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', flag: '🇹🇴' },
  { code: 'TR', name: 'Turkey', currency: 'TRY', flag: '🇹🇷' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', flag: '🇹🇹' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', flag: '🇹🇻' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', flag: '🇹🇿' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', currency: 'UGX', flag: '🇺🇬' },
  { code: 'UM', name: 'United States Minor Outlying Islands', currency: 'USD', flag: '🇺🇲' },
  { code: 'US', name: 'United States', currency: 'USD', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', flag: '🇺🇿' },
  { code: 'VA', name: 'Vatican City', currency: 'EUR', flag: '🇻🇦' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', currency: 'XCD', flag: '🇻🇨' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', flag: '🇻🇪' },
  { code: 'VG', name: 'British Virgin Islands', currency: 'USD', flag: '🇻🇬' },
  { code: 'VI', name: 'U.S. Virgin Islands', currency: 'USD', flag: '🇻🇮' },
  { code: 'VN', name: 'Vietnam', currency: 'VND', flag: '🇻🇳' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', flag: '🇻🇺' },
  { code: 'WF', name: 'Wallis and Futuna', currency: 'XPF', flag: '🇼🇫' },
  { code: 'WS', name: 'Samoa', currency: 'WST', flag: '🇼🇸' },
  { code: 'YE', name: 'Yemen', currency: 'YER', flag: '🇾🇪' },
  { code: 'YT', name: 'Mayotte', currency: 'EUR', flag: '🇾🇹' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', flag: '🇿🇦' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWL', flag: '🇿🇼' }
];

export const getCountryByCode = (code: string): Country | undefined => {
  return countries.find(country => country.code === code);
};

export const getCountriesByCurrency = (currency: string): Country[] => {
  return countries.filter(country => country.currency === currency);
};