export interface Currency {
  code: string;
  name: string;
  symbol: string;
  decimals: number;
}

export const currencies: Currency[] = [
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', decimals: 2 },
  { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', decimals: 2 },
  { code: 'ALL', name: 'Albanian Lek', symbol: 'L', decimals: 2 },
  { code: 'AMD', name: 'Armenian Dram', symbol: '֏', decimals: 2 },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', decimals: 2 },
  { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', decimals: 2 },
  { code: 'ARS', name: 'Argentine Peso', symbol: '$', decimals: 2 },
  { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', decimals: 2 },
  { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', decimals: 2 },
  { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', decimals: 2 },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', decimals: 2 },
  { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', decimals: 2 },
  { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', decimals: 2 },
  { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', decimals: 2 },
  { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', decimals: 3 },
  { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', decimals: 0 },
  { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', decimals: 2 },
  { code: 'BND', name: 'Brunei Dollar', symbol: '$', decimals: 2 },
  { code: 'BOB', name: 'Bolivian Boliviano', symbol: '$b', decimals: 2 },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', decimals: 2 },
  { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', decimals: 2 },
  { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', decimals: 2 },
  { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', decimals: 2 },
  { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', decimals: 2 },
  { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', decimals: 2 },
  { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', decimals: 2 },
  { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', decimals: 2 },
  { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', decimals: 2 },
  { code: 'CLP', name: 'Chilean Peso', symbol: '$', decimals: 0 },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', decimals: 2 },
  { code: 'COP', name: 'Colombian Peso', symbol: '$', decimals: 2 },
  { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', decimals: 2 },
  { code: 'CUP', name: 'Cuban Peso', symbol: '₱', decimals: 2 },
  { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', decimals: 2 },
  { code: 'CZK', name: 'Czech Republic Koruna', symbol: 'Kč', decimals: 2 },
  { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', decimals: 0 },
  { code: 'DKK', name: 'Danish Krone', symbol: 'kr', decimals: 2 },
  { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', decimals: 2 },
  { code: 'DZD', name: 'Algerian Dinar', symbol: 'دج', decimals: 2 },
  { code: 'EGP', name: 'Egyptian Pound', symbol: '£', decimals: 2 },
  { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', decimals: 2 },
  { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', decimals: 2 },
  { code: 'EUR', name: 'Euro', symbol: '€', decimals: 2 },
  { code: 'FJD', name: 'Fijian Dollar', symbol: '$', decimals: 2 },
  { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', decimals: 2 },
  { code: 'GBP', name: 'British Pound Sterling', symbol: '£', decimals: 2 },
  { code: 'GEL', name: 'Georgian Lari', symbol: '₾', decimals: 2 },
  { code: 'GHS', name: 'Ghanaian Cedi', symbol: '¢', decimals: 2 },
  { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', decimals: 2 },
  { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', decimals: 2 },
  { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', decimals: 0 },
  { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', decimals: 2 },
  { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', decimals: 2 },
  { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', decimals: 2 },
  { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', decimals: 2 },
  { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', decimals: 2 },
  { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', decimals: 2 },
  { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', decimals: 2 },
  { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', decimals: 2 },
  { code: 'ILS', name: 'Israeli New Sheqel', symbol: '₪', decimals: 2 },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', decimals: 2 },
  { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', decimals: 3 },
  { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', decimals: 2 },
  { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', decimals: 0 },
  { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', decimals: 2 },
  { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', decimals: 3 },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', decimals: 0 },
  { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', decimals: 2 },
  { code: 'KGS', name: 'Kyrgystani Som', symbol: 'лв', decimals: 2 },
  { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', decimals: 2 },
  { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', decimals: 0 },
  { code: 'KPW', name: 'North Korean Won', symbol: '₩', decimals: 2 },
  { code: 'KRW', name: 'South Korean Won', symbol: '₩', decimals: 0 },
  { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'KD', decimals: 3 },
  { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', decimals: 2 },
  { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', decimals: 2 },
  { code: 'LAK', name: 'Laotian Kip', symbol: '₭', decimals: 2 },
  { code: 'LBP', name: 'Lebanese Pound', symbol: '£', decimals: 2 },
  { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', decimals: 2 },
  { code: 'LRD', name: 'Liberian Dollar', symbol: '$', decimals: 2 },
  { code: 'LSL', name: 'Lesotho Loti', symbol: 'M', decimals: 2 },
  { code: 'LYD', name: 'Libyan Dinar', symbol: 'LD', decimals: 3 },
  { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', decimals: 2 },
  { code: 'MDL', name: 'Moldovan Leu', symbol: 'lei', decimals: 2 },
  { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', decimals: 2 },
  { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', decimals: 2 },
  { code: 'MMK', name: 'Myanma Kyat', symbol: 'K', decimals: 2 },
  { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', decimals: 2 },
  { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', decimals: 2 },
  { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', decimals: 2 },
  { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', decimals: 2 },
  { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', decimals: 2 },
  { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', decimals: 2 },
  { code: 'MXN', name: 'Mexican Peso', symbol: '$', decimals: 2 },
  { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', decimals: 2 },
  { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', decimals: 2 },
  { code: 'NAD', name: 'Namibian Dollar', symbol: '$', decimals: 2 },
  { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', decimals: 2 },
  { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', decimals: 2 },
  { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', decimals: 2 },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', decimals: 2 },
  { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', decimals: 2 },
  { code: 'OMR', name: 'Omani Rial', symbol: '﷼', decimals: 3 },
  { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', decimals: 2 },
  { code: 'PEN', name: 'Peruvian Nuevo Sol', symbol: 'S/.', decimals: 2 },
  { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', decimals: 2 },
  { code: 'PHP', name: 'Philippine Peso', symbol: '₱', decimals: 2 },
  { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', decimals: 2 },
  { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', decimals: 2 },
  { code: 'PYG', name: 'Paraguayan Guarani', symbol: 'Gs', decimals: 0 },
  { code: 'QAR', name: 'Qatari Rial', symbol: '﷼', decimals: 2 },
  { code: 'RON', name: 'Romanian Leu', symbol: 'lei', decimals: 2 },
  { code: 'RSD', name: 'Serbian Dinar', symbol: 'Дин.', decimals: 2 },
  { code: 'RUB', name: 'Russian Ruble', symbol: '₽', decimals: 2 },
  { code: 'RWF', name: 'Rwandan Franc', symbol: 'R₣', decimals: 0 },
  { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', decimals: 2 },
  { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', decimals: 2 },
  { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', decimals: 2 },
  { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', decimals: 2 },
  { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', decimals: 2 },
  { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', decimals: 2 },
  { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', decimals: 2 },
  { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', decimals: 2 },
  { code: 'SOS', name: 'Somali Shilling', symbol: 'S', decimals: 2 },
  { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', decimals: 2 },
  { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', decimals: 2 },
  { code: 'STN', name: 'São Tomé and Príncipe Dobra', symbol: 'Db', decimals: 2 },
  { code: 'SYP', name: 'Syrian Pound', symbol: '£', decimals: 2 },
  { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'E', decimals: 2 },
  { code: 'THB', name: 'Thai Baht', symbol: '฿', decimals: 2 },
  { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'SM', decimals: 2 },
  { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', decimals: 2 },
  { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', decimals: 3 },
  { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', decimals: 2 },
  { code: 'TRY', name: 'Turkish Lira', symbol: '₺', decimals: 2 },
  { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', decimals: 2 },
  { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', decimals: 2 },
  { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', decimals: 2 },
  { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', decimals: 2 },
  { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', decimals: 0 },
  { code: 'USD', name: 'United States Dollar', symbol: '$', decimals: 2 },
  { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', decimals: 2 },
  { code: 'UZS', name: 'Uzbekistan Som', symbol: 'лв', decimals: 2 },
  { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs', decimals: 2 },
  { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', decimals: 0 },
  { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', decimals: 0 },
  { code: 'WST', name: 'Samoan Tala', symbol: 'WS$', decimals: 2 },
  { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA', decimals: 0 },
  { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', decimals: 2 },
  { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA', decimals: 0 },
  { code: 'XPF', name: 'CFP Franc', symbol: '₣', decimals: 0 },
  { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', decimals: 2 },
  { code: 'ZAR', name: 'South African Rand', symbol: 'R', decimals: 2 },
  { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', decimals: 2 },
  { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: 'Z$', decimals: 2 }
];

export const getCurrencyByCode = (code: string): Currency | undefined => {
  return currencies.find(currency => currency.code === code);
};

export const formatCurrency = (amount: number, currencyCode: string): string => {
  const currency = getCurrencyByCode(currencyCode);
  if (!currency) return `${amount.toFixed(2)}`;
  
  return `${currency.symbol}${amount.toFixed(currency.decimals)}`;
};

export const getMajorCurrencies = (): Currency[] => {
  const majorCodes = ['USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'SEK', 'NZD'];
  return currencies.filter(currency => majorCodes.includes(currency.code));
};